name: Build and Publish Private NPM Package 
on:
  push:
    branches:
      - develop
 
jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@themetzmeier'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Publish New Version
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}